### ISSUE TITLE
API for weather Web-Service (REST)

### ISSUE THREAD

**Issue by aschitnis** [aschitnis/my-projects#2]
- a Class which implements the functions for calls to the webservice. Note, WebService calls are made over REST.
- The password.key and the URL for the Web Service should be kept separately in a static Class file. Or maybe in the API class file

**Comment by abi-gmail-github** [comment]
- added a new static class for all constants. z.b. The http URL for weather WS.
- added Json data modelling class
- added Json convertor class (To convert the values in Json e.g. decimal to string etc.)

**Comment by abi-gmail-github** [comment]
Closed the Issue out of human Error. Reopened it again.

**Comment by abi-gmail-github** [comment]
- Added APIAccess class for Http REST service call. The call returns a Json string if successful otherwise the Method returns a Exception.
-
